### ISSUE TITLE
pkg alacarte: No module named gi

### ISSUE THREAD

**Issue by peter1000** [NuTyX/gnome#5]
hi

```bash
root [ ~ ]# cards install alacarte
Retrieve info about the 483 packages: 100 %
REMOVE: alacarte 3.11.91-1, 31 files: 100 %
ADD   : alacarte 3.11.91-1, 52 files: 100 %
root [ ~ ]# alacarte
Traceback (most recent call last):
  File "/usr/bin/alacarte", line 21, in <module>
    from Alacarte.MainWindow import main
  File "/usr/lib/python2.7/site-packages/Alacarte/MainWindow.py", line 20, in <module>
    import gi
ImportError: No module named gi
```

 just wanted to let you know that pkg `alacarte` throws this error here. Should the dependencies not pulled in automatically?

[Add a package](https://github.com/NuTyX/houaphan/blob/master/www/en/base-commands.html#L68)

```
once the package is downloads, it's dependencies will be downloads as well.
When all done with the download, all the packages will be installed in the right order. 
```

**Comment by tnut** [comment]
will add python as runtime dep
